version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cars
      MYSQL_DATABASE: commercecars
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"